FROM openeuler/openeuler:23.09

# RUN sed -i "s#http://repo.openeuler.org#https://repo.huaweicloud.com/openeuler#g" /etc/yum.repos.d/openEuler.repo

RUN set -eux; \
yum -y install git java tar cmake gperf sqlite-devel libffi-devel xz-devel \
zlib zlib-devel openssl-devel bzip2-devel ncurses-devel readline-devel \
libpcap-devel parted autoconf-archive chrpath gcc-c++ patch rpm-build flex \
autoconf automake m4 bison bc libtool gettext-devel createrepo_c net-tools \
wget sudo hostname rpcgen texinfo python meson dosfstools mtools libmpc-devel \
gmp-devel ninja-build numactl-devel make python3 python3-pip screen glibc-locale-archive iproute \
xz unzip help2man libstdc++-static gcc g++ rsync python3-devel gdisk \
vim hwdata libxslt perl-XML-Parser umoci skopeo

ARG user=openeuler
ARG group=openeuler
ARG uid=1000
ARG gid=1000

# add build user
RUN groupadd -g ${gid} ${group} && useradd -c "${user}" -d /home/${user} -u ${uid} -g ${gid} -m ${user}
RUN echo "${user} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# modify /usr1 owner
RUN mkdir -p /usr1 && chown -R ${user}:${group} /usr1 /opt && chmod -R 755 /usr1 /opt

# install nativesdk toolchains and environment of build toolchains
# notice: nativesdk and toolchains is for building OS

# modify default configs
RUN sed -i 's/TMOUT=300/TMOUT=/g' /etc/bashrc

# add umask conf to 022 in file /etc/bashrc
RUN echo "umask 022" >> /etc/bashrc

USER openeuler

RUN mkdir -p /opt/buildtools/nativesdk/crosstool-ng

WORKDIR /opt/buildtools/nativesdk/crosstool-ng

RUN wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.26.0.tar.bz2

RUN tar jxvf crosstool-ng-1.26.0.tar.bz2

RUN ./crosstool-ng-1.26.0/configure

RUN make

RUN sudo make install

RUN mkdir -p /opt/buildtools/nativesdk/sdk_info
# download nativesdk release
WORKDIR /opt/buildtools/nativesdk/sdk_info

RUN wget https://gitee.com/openeuler/yocto-meta-openeuler/releases/download/nativesdk-v0.1.2/x86_64-buildtools-extended-nativesdk-standalone-24.03-LTS.testdata.json

RUN wget https://gitee.com/openeuler/yocto-meta-openeuler/releases/download/nativesdk-v0.1.2/1_x86_64-buildtools-extended-nativesdk-standalone-24.03-LTS.sh

RUN wget https://gitee.com/openeuler/yocto-meta-openeuler/releases/download/nativesdk-v0.1.2/2_x86_64-buildtools-extended-nativesdk-standalone-24.03-LTS.sh

RUN wget https://gitee.com/openeuler/yocto-meta-openeuler/releases/download/nativesdk-v0.1.2/3_x86_64-buildtools-extended-nativesdk-standalone-24.03-LTS.sh

RUN wget https://gitee.com/openeuler/yocto-meta-openeuler/releases/download/nativesdk-v0.1.2/x86_64-buildtools-extended-nativesdk-standalone-24.03-LTS.target.manifest

RUN wget https://gitee.com/openeuler/yocto-meta-openeuler/releases/download/nativesdk-v0.1.2/x86_64-buildtools-extended-nativesdk-standalone-24.03-LTS.host.manifest

RUN wget https://gitee.com/openeuler/yocto-meta-openeuler/releases/download/nativesdk-v0.1.2/merge_data.sh

RUN bash ./merge_data.sh

RUN ./x86_64-buildtools-extended-nativesdk-standalone-24.03-LTS.sh -d /opt/buildtools/nativesdk -y && chmod -R 777 /opt/buildtools/nativesdk

RUN . /opt/buildtools/nativesdk/environment-setup-x86_64-openeulersdk-linux

RUN mkdir -p /usr1/openeuler/gcc

COPY gcc /usr1/openeuler/gcc

RUN sudo chmod -R 777 /usr1/openeuler/gcc && sudo chown -R ${user}:${group} /usr1

RUN pip install pyyaml pygit gitpython -i https://pypi.tuna.tsinghua.edu.cn/simple

RUN rm -rf /opt/buildtools/nativesdk/crosstool-ng

RUN rm -rf /opt/buildtools/nativesdk/sdk_info

RUN rm -rf /crosstool-ng-1.26.0